package IHM.ResponsableFormation;

import AdmissionPostLicence.Ministere;
import AdmissionPostLicence.Rectorat;
import Util.GetObjectCorba;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

/**
 *
 * @author Teddy
 */
public class Login extends javax.swing.JFrame {
    
    private final org.omg.CORBA.ORB orb;
    private final Ministere ministere;
    
    private final String comboDefault = "Sélectionnez";
    private final String comboDefaultUniversite = "Sélectionnez un rectorat";
    
    private HashMap<String,Rectorat> rectorats = new HashMap<>();
    
    private Rectorat rectoratSel;
    
    private final String loginAdmin = "admin";
    private final String mdpAdmin = "admin";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        // Initialisation de l'orb
        String[] argsOrb = {};
        orb = org.omg.CORBA.ORB.init(argsOrb, null);
        orb.string_to_object("corbaloc:iiop:1.2@192.168.0.13:2001/NameService");
        
        // Récupération du ministère
        ministere = GetObjectCorba.getMinistereCorba(orb);
        
        // Récupération de la liste des rectorats
        String[] iorRectorats = ministere.getListeRectorat();
        Rectorat r;
        
        // Remplissage de la liste déroulante
        for(String ior : iorRectorats) {
            r = GetObjectCorba.getRectoratCorba(orb, ior);
            if( r != null) {
                rectorats.put(r.nom(), r);
                rectoratComboBox.addItem(r.nom());
            }
        }
        
        // Récupère les universités une fois un rectorat sélectionné
        rectoratComboBox.addActionListener (new ActionListener () {
            @Override
            public void actionPerformed(ActionEvent ae) {
                // Récupération du rectorat sélectionné
                String rectorat = (String) rectoratComboBox.getSelectedItem();
                
                if(!rectorat.equals(comboDefault)) {
                    // On récupère l'objet corba du rectorat
                    rectoratSel = rectorats.get(rectorat);
                    
                    // Récupération de la liste des universités                    
                    List<String> universites = new ArrayList<>(Arrays.asList(rectoratSel.getListeUniversite()));
                    
                    // Remplissage de la liste déroulante
                    for(String universite : universites) {
                        universiteComboBox.addItem(universite);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        mdpTextField = new javax.swing.JTextField();
        universiteComboBox = new javax.swing.JComboBox();
        rectoratComboBox = new javax.swing.JComboBox();
        loginButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formation - Gestion des admissions");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Connexion");

        jLabel3.setText("Login :");

        jLabel4.setText("Mot de passe :");

        jLabel5.setText("Université :");

        jLabel6.setText("Rectorat :");

        universiteComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionnez un rectorat" }));

        rectoratComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionnez" }));

        loginButton.setText("Se connecter");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(loginButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mdpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(loginTextField)
                                    .addComponent(rectoratComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(universiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mdpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rectoratComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(universiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // Récupération des valeurs du formulaire de connexion
        String login = loginTextField.getText();
        String mdp = mdpTextField.getText();
        String rectorat = (String) rectoratComboBox.getSelectedItem();
        String universite = (String) universiteComboBox.getSelectedItem();
        
        if(login.isEmpty() || mdp.isEmpty() || rectorat.equals(comboDefaultUniversite) || universite.equals(comboDefault)) {
            // Affichage d'un message d'erreur
            errorLabel.setText("Tous les champs son obligatoires !");
        } else {
            // Masquer le message d'erreur
            errorLabel.setText("");
            
            // Vérification du couple login/mdp
            if(loginAdmin.equals(login) && mdpAdmin.equals(mdp)) {
                    // On affiche la fenêtre de gestion des candidatures
                    Principal m = new Principal(rectoratSel, universite);
                    m.setVisible(true);
                    // Et on masque la fenêtre de connexion
                    this.setVisible(false);
            } else {
                // Affichage d'un message d'erreur
                errorLabel.setText("Le couple login / mot de passe est incorrect !");
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField mdpTextField;
    private javax.swing.JComboBox rectoratComboBox;
    private javax.swing.JComboBox universiteComboBox;
    // End of variables declaration//GEN-END:variables
}
