package IHM.ResponsableFormation;

import AdmissionPostLicence.resultatsEtudiant;

/**
 *
 * @author Teddy
 */
public class NotesEtudiantPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotesEtudiantPanel
     * @param desResultats
     */
    public NotesEtudiantPanel(resultatsEtudiant desResultats) {
        initComponents();
        
        // Afficahge des informations de l'étudiant
        prenomLabel.setText(desResultats.etudiant.prenom);
        nomLabel.setText(desResultats.etudiant.nom);
        ineLabel.setText("(" + desResultats.etudiant.ine + ")");
        licenceLabel.setText(desResultats.etudiant.licence);
                
        // Affichage des résultats dans le tableau
        notesTable.setModel(new ResultatModel(desResultats.resultatsSemestres));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        ineLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        licenceLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesTable = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Etudiant :");

        prenomLabel.setText("Prénom");

        nomLabel.setText("NOM");

        ineLabel.setText("(INE)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Résultats semestres licence");

        licenceLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        licenceLabel.setText("jLabel3");

        notesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Semestre", "Moyenne", "Classement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        notesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(notesTable);
        if (notesTable.getColumnModel().getColumnCount() > 0) {
            notesTable.getColumnModel().getColumn(0).setResizable(false);
            notesTable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(prenomLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nomLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ineLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(licenceLabel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(prenomLabel)
                    .addComponent(nomLabel)
                    .addComponent(ineLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(licenceLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ineLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel licenceLabel;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTable notesTable;
    private javax.swing.JLabel prenomLabel;
    // End of variables declaration//GEN-END:variables
}
