package responsableFormation;

import AdmissionPostLicence.CandidatureInconnu;
import AdmissionPostLicence.EtudiantInconnu;
import AdmissionPostLicence.GestionEtudiant;
import AdmissionPostLicence.Master;
import AdmissionPostLicence.candidature;
import AdmissionPostLicence.decisionMaster;
import AdmissionPostLicence.etatCandidature;
import AdmissionPostLicence.resultatsEtudiant;
import Util.GetObjectCorba;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.omg.CORBA.ORB;

/**
 *
 * 
 */
public class CandidaturePanel extends javax.swing.JPanel {

    private final ORB orb;
    
    private final candidature candidature;
    private final Master master;
    private final GestionEtudiant gestionEtudiant;
    
    /**
     * Creates new form CandidaturePanel
     * @param uneCandidature
     * @param unMaster
     * @param uneGestionEtudiant
     * @param unOrb
     */
    public CandidaturePanel(candidature uneCandidature, Master unMaster, GestionEtudiant uneGestionEtudiant, ORB unOrb) {
        initComponents();
        
        candidature = uneCandidature;
        master = unMaster;
        gestionEtudiant = uneGestionEtudiant;
        
        orb = unOrb;
        
        ineLabel.setText(candidature.etudiant.ine);
        nomLabel.setText(candidature.etudiant.nom);
        prenomLabel.setText(candidature.etudiant.prenom);
        universiteLabel.setText(candidature.etudiant.universite);
        licenceLabel.setText(candidature.etudiant.licence);
        
        decisionComboBox.setSelectedItem(convertDecisionMasterToString(candidature.decisionM));
    }
    
    private String convertDecisionMasterToString(decisionMaster decision) {
        String retour;
        
        switch(decision.toString()) {
            case "admis":
                retour = "Admis";
                break;
            case "listeAttente":
                retour = "Attente";
                break;
            case "refuser":
                retour = "Refus";
                break;
            case "nonTraite":
                retour = "Non traité";
                break;
            default:
                retour = "";
                break;
        }
        
        return retour;
    }
    
    /**
     * 
     * @param decision
     * @return {@link decisionMaster}
     */
    private decisionMaster convertStringToDecisionMaster(String decision) {
        decisionMaster retour = null;
        
        if(convertDecisionMasterToString(decisionMaster.admis).equals(decision)) {
            retour = decisionMaster.admis;
        } else if(convertDecisionMasterToString(decisionMaster.listeAttente).equals(decision)) {
            retour = decisionMaster.listeAttente;
        } else if(convertDecisionMasterToString(decisionMaster.refuser).equals(decision)) {
            retour = decisionMaster.refuser;
        } else if(convertDecisionMasterToString(decisionMaster.nonTraite).equals(decision)) {
            retour = decisionMaster.nonTraite;
        }
        
        return retour;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etudiantLabel = new javax.swing.JLabel();
        decisionComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        universiteLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        licenceLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ineLabel = new javax.swing.JLabel();
        notesButton = new javax.swing.JButton();
        enregistrerButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etudiantLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etudiantLabel.setText("Informations de l'étudiant");

        decisionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionnez", "Non traité", "Admis", "Attente", "Refus" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Décision :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nom :");

        nomLabel.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Prénom :");

        prenomLabel.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Université :");

        universiteLabel.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Licence :");

        licenceLabel.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("INE :");

        ineLabel.setText("jLabel11");

        notesButton.setText("Voir notes");
        notesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesButtonActionPerformed(evt);
            }
        });

        enregistrerButton.setText("Enregistrer");
        enregistrerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etudiantLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(decisionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(enregistrerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(22, 22, 22)
                        .addComponent(ineLabel)
                        .addGap(18, 18, 18)
                        .addComponent(notesButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nomLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(prenomLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(universiteLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(licenceLabel)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etudiantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ineLabel)
                    .addComponent(notesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomLabel)
                    .addComponent(jLabel4)
                    .addComponent(prenomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(universiteLabel)
                    .addComponent(jLabel8)
                    .addComponent(licenceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(decisionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enregistrerButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void notesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesButtonActionPerformed
        try {
            // Récupération des résultats de l'étudiant
            GestionEtudiant ge = GetObjectCorba.getGestionEtudiantCorba(candidature.etudiant.universite, orb);
            resultatsEtudiant resultats = ge.recupererResultats(candidature.etudiant);
            
            // Affichage des notes
            JFrame fenetreNotes = new JFrame("Notes étudiant");
            fenetreNotes.setContentPane(new NotesEtudiantPanel(resultats));
            fenetreNotes.pack();
            fenetreNotes.setVisible(true);
        } catch (EtudiantInconnu ex) {
            // Affichage d'une pop-up
            JOptionPane.showMessageDialog(this, "Une erreur est survenue lors de la récupération des notes",
                    "Gestion des candidatures", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_notesButtonActionPerformed

    private void enregistrerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerButtonActionPerformed
        // On récupère la décision du responsable
        String decisionSel = (String) decisionComboBox.getSelectedItem();
        decisionMaster decision = convertStringToDecisionMaster(decisionSel);
        
        if(decision != null) {
            candidature.decisionM = decision;
            candidature.etat = etatCandidature.cloture;
            try {
                // On transmet la décision à l'université
                master.modifierDecision(candidature);
                // Affichage d'une pop-up
                JOptionPane.showMessageDialog(this, "Décision enregistrée", "Admission post licence", JOptionPane.INFORMATION_MESSAGE);
            } catch (CandidatureInconnu ex) {
                // Affichage d'une pop-up
                JOptionPane.showMessageDialog(this, "Une erreur est survenue lors de l'enregistrement de la décision",
                    "Gestion des candidatures", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_enregistrerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox decisionComboBox;
    private javax.swing.JButton enregistrerButton;
    private javax.swing.JLabel etudiantLabel;
    private javax.swing.JLabel ineLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel licenceLabel;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JButton notesButton;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JLabel universiteLabel;
    // End of variables declaration//GEN-END:variables
}
