package gestionEtape;

import AdmissionPostLicence.Ministere;
import AdmissionPostLicence.periode;
import Util.GetObjectCorba;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 * 
 */
public class MainWindow extends javax.swing.JFrame {
    
    private final org.omg.CORBA.ORB orb;
    private final Ministere ministere;
    
    private final String comboDefault = "Sélectionnez";
    
    private periode periodeEnCours;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        // Initialisation de l'orb
        String[] argsOrb = {};
        orb = org.omg.CORBA.ORB.init(argsOrb, null);
        orb.string_to_object("corbaloc:iiop:1.2@" + GetObjectCorba.getIpServeur() + ":2001/NameService");
        
        // Récupération du ministère
        ministere = GetObjectCorba.getMinistereCorba(orb);
        
        // Récupération de la phase en cours
        periodeEnCours = ministere.periodeEnCours();
        etapeEnCoursLabel.setText(periodeEnCours.toString());
        
        // Remplissage menu déroulant du choix de la période
        choixEtapeComboBox.addItem(periode.periode1.toString());
        choixEtapeComboBox.addItem(periode.periode2.toString());
        choixEtapeComboBox.addItem(periode.periode3.toString());
        choixEtapeComboBox.addItem(periode.periode4.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        etapeEnCoursLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        choixEtapeComboBox = new javax.swing.JComboBox();
        etapeSuivanteButton = new javax.swing.JButton();
        validerChoixEtapeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admission des licences - gestion des étapes");

        jLabel1.setText("Etape en cours :");

        etapeEnCoursLabel.setText("jLabel2");

        jLabel2.setText("Aller à l'étape :");

        choixEtapeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionnez" }));

        etapeSuivanteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etapeSuivanteButton.setText("ETAPE SUIVANTE");
        etapeSuivanteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etapeSuivanteButtonActionPerformed(evt);
            }
        });

        validerChoixEtapeButton.setText("Valider");
        validerChoixEtapeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerChoixEtapeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(choixEtapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(validerChoixEtapeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(etapeEnCoursLabel))
                            .addComponent(etapeSuivanteButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etapeEnCoursLabel))
                .addGap(18, 18, 18)
                .addComponent(etapeSuivanteButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(choixEtapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validerChoixEtapeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etapeSuivanteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etapeSuivanteButtonActionPerformed
        int phaseSuivante = periodeEnCours.value() + 1;
        if(phaseSuivante <= 3) {
            periodeEnCours = periode.from_int(phaseSuivante);
        }
        majEtapeEnCours();
    }//GEN-LAST:event_etapeSuivanteButtonActionPerformed

    private void validerChoixEtapeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerChoixEtapeButtonActionPerformed
        String periodeSel = (String) choixEtapeComboBox.getSelectedItem();
                
        if(!periodeSel.equals(comboDefault)) {
            switch(periodeSel) {
                case "periode1":
                    periodeEnCours = periode.periode1;
                    break;
                case "periode2":
                    periodeEnCours = periode.periode2;
                    break;
                case "periode3":
                    periodeEnCours = periode.periode3;
                    break;
                case "periode4":
                    periodeEnCours = periode.periode4;
                    break;
            }
            majEtapeEnCours();
            
            // Affichage d'une pop-up
            JOptionPane.showMessageDialog(this, "Changement période effectué", "Admission post licence", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_validerChoixEtapeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    private void majEtapeEnCours() {
        ministere.periodeEnCours(periodeEnCours);
        etapeEnCoursLabel.setText(periodeEnCours.toString());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox choixEtapeComboBox;
    private javax.swing.JLabel etapeEnCoursLabel;
    private javax.swing.JButton etapeSuivanteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton validerChoixEtapeButton;
    // End of variables declaration//GEN-END:variables
}
